<Project>

  <PropertyGroup>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Filipe Toscano</Authors>
    <Product>.NET tool for XML files</Product>
    <Copyright>Copyright © Filipe Toscano</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/filipetoscano/xml/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/filipetoscano/xml.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <DebugType>portable</DebugType>

    <!-- Packaging properties -->
    <IsPackable>false</IsPackable>
    <PackageDescription>.NET tool for XML files</PackageDescription>
    <PackageIconUrl>https://media.githubusercontent.com/media/filipetoscano/xml/master/docs/img/icon.png</PackageIconUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>xml</PackageTags>

    <!-- Debuging properties -->
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Condition=" '$(IsPackable)' == 'true' ">
    <None Include="$(MSBuildThisFileDirectory)docs\img\icon.png">
      <Pack>true</Pack>
      <PackagePath>/$(PackageIcon)</PackagePath>
      <Visible>false</Visible>
    </None>
  </ItemGroup>

</Project>